<a href="https://colab.research.google.com/github/Venkatesh0406/python/blob/main/ad_day_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
k=[4,2.4554,76.983,'hyd']


In [3]:
k

[4, 2.4554, 76.983, 'hyd']

In [4]:
pd.Series(k)

0         4
1    2.4554
2    76.983
3       hyd
dtype: object

In [5]:
a=np.random.randint(20,50,15)
a

array([38, 42, 40, 49, 37, 42, 35, 29, 41, 40, 41, 49, 31, 28, 39])

In [6]:
pd.Series(a)

0     38
1     42
2     40
3     49
4     37
5     42
6     35
7     29
8     41
9     40
10    41
11    49
12    31
13    28
14    39
dtype: int64

In [7]:
a[4:10]

array([37, 42, 35, 29, 41, 40])

In [8]:
s=pd.Series(a)

In [9]:
s

0     38
1     42
2     40
3     49
4     37
5     42
6     35
7     29
8     41
9     40
10    41
11    49
12    31
13    28
14    39
dtype: int64

In [10]:
s[4:10]

4    37
5    42
6    35
7    29
8    41
9    40
dtype: int64

In [13]:
b=np.random.randint(100,299,(6,5))

In [14]:
b

array([[114, 228, 264, 287, 285],
       [159, 214, 208, 212, 233],
       [212, 215, 246, 164, 164],
       [140, 106, 166, 177, 170],
       [178, 298, 118, 124, 154],
       [241, 286, 175, 136, 102]])

In [15]:
b.ndim

2

In [17]:
pd.DataFrame(b)

0    1    2    3    4
0  114  228  264  287  285
1  159  214  208  212  233
2  212  215  246  164  164
3  140  106  166  177  170
4  178  298  118  124  154
5  241  286  175  136  102

In [18]:
df=pd.DataFrame(b,columns=['Roll','name','age','adds','country'])
df

Roll  name  age  adds  country
0   114   228  264   287      285
1   159   214  208   212      233
2   212   215  246   164      164
3   140   106  166   177      170
4   178   298  118   124      154
5   241   286  175   136      102

In [20]:
df=pd.DataFrame(b,columns=['Roll','name','age','adds','country'],index=[182,183,185,186,187,188])
df

Roll  name  age  adds  country
182   114   228  264   287      285
183   159   214  208   212      233
185   212   215  246   164      164
186   140   106  166   177      170
187   178   298  118   124      154
188   241   286  175   136      102

In [21]:
df.loc[182]

Roll       114
name       228
age        264
adds       287
country    285
Name: 182, dtype: int64

In [22]:
df.iloc[0,0]

114

In [23]:
df.loc[182,['Roll','name','age']]

Roll    114
name    228
age     264
Name: 182, dtype: int64

In [25]:
df.iloc[[1,3,4]]

Roll  name  age  adds  country
183   159   214  208   212      233
186   140   106  166   177      170
187   178   298  118   124      154

In [27]:
df.loc[[183,186,187]]

Roll  name  age  adds  country
183   159   214  208   212      233
186   140   106  166   177      170
187   178   298  118   124      154

In [28]:
df.age

182    264
183    208
185    246
186    166
187    118
188    175
Name: age, dtype: int64

In [29]:
df[['age','adds']]

age  adds
182  264   287
183  208   212
185  246   164
186  166   177
187  118   124
188  175   136